#cloud-config
groups:
  - storage-l1
  - storage-cam
users:
  - name: ${USER_NAME}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: storage-l1
    ssh_authorized_keys:
      - \"${SSH_KEY}\"

  - name: wwwuser
    shell: /bin/bash
    system: true
    groups: storage-l1

package_upgrade: true
packages:
  - wireguard
  - podman
  - slirp4netns
  - systemd-container
  - cifs-utils
  - git-lfs

write_files:
# wireguard
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      PrivateKey = ${WG_PRIV_KEY}
      ListenPort = 13231
      Address = 172.16.16.1/24

      [Peer]
      PublicKey = ${WG_PUB_KEY}
      AllowedIPs = 172.16.16.90/32
    permissions: '0600'

  - path: /etc/systemd/system/wg-quick@.service.d/override.conf
    content: |
      [Unit]
      Before=ssh.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
    permissions: '0644'

# sshd
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      Protocol 2
      PermitRootLogin no
      PubkeyAuthentication yes
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM no
      X11Forwarding no
      AllowTcpForwarding no
      AllowAgentForwarding no
      PermitTunnel no
      PrintMotd yes
      AcceptEnv LANG LC_*
      AllowUsers ${USER_NAME}
      ListenAddress 172.16.16.1
    permissions: '0600'

# sysctl
  - path: /etc/sysctl.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1
      vm.swappiness = 10
      vm.vfs_cache_pressure=50
      vm.overcommit_memory = 1
    permissions: '0644'

# envncreds
  - path: /root/.envncreds
    content: |
      USER_NAME=${USER_NAME}
      STORAGE_L1=${STORAGE_L1}
      STORAGE_CAM=${STORAGE_CAM}
    permissions: '0600'

swap:
  filename: /swapfile
  size: auto

runcmd:
  - [usermod, -p, '*', ${USER_NAME}]
  - [systemctl, daemon-reload]
  - [systemctl, enable, wg-quick@wg0]
  - [systemctl, start, wg-quick@wg0]
  - [systemctl, restart, ssh]
  - [git, clone, https://github.com/heroalex/server.git, /root/server]
  - [chmod, +x, /root/server/scripts/init_server.sh]
  - [/root/server/scripts/init_server.sh]

power_state:
  mode: reboot
  timeout: 300
  condition: True