#cloud-config
users:
  - name: ${USER_NAME}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    uid: 1000
    ssh_authorized_keys:
      - \"${SSH_KEY}\"

  - name: nginxuser
    shell: /bin/bash
    system: true
    uid: 999

  - name: storage_l1
    shell: /bin/bash
    system: true
    uid: 998

package_upgrade: false
packages:
#  - wireguard
  - podman
#  - lxd
  - systemd-container
  - cifs-utils

write_files:
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      PrivateKey = ${WG_PRIV_KEY}
      ListenPort = 13231
      Address = 172.16.16.1/24

      [Peer]
      PublicKey = ${WG_PUB_KEY}
      AllowedIPs = 172.16.16.90/32
    permissions: '0600'

  - path: /etc/systemd/system/wg-quick@.service.d/override.conf
    content: |
      [Unit]
      Before=ssh.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
    permissions: '0644'

  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      Protocol 2
      PermitRootLogin no
      PubkeyAuthentication yes
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM no
      X11Forwarding no
      AllowTcpForwarding no
      AllowAgentForwarding no
      PermitTunnel no
      PrintMotd yes
      AcceptEnv LANG LC_*
      AllowUsers ${USER_NAME}
      ListenAddress 172.16.16.1
    permissions: '0600'

  - path: /etc/sysctl.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1
      vm.swappiness = 10
      vm.vfs_cache_pressure=50
      vm.overcommit_memory = 1
      net.ipv4.ip_unprivileged_port_start=80
    permissions: '0644'

  - path: /etc/systemd/system/storage-L1.mount
    content: |
      [Unit]
      Description=Hetzner Storage Box CIFS Mount L1
      Requires=network-online.target
      After=network-online.target
      
      [Mount]
      What=//u324047-sub5.your-storagebox.de/u324047-sub5
      Where=/mnt/storage-L1
      Type=cifs
      Options=vers=3.0,credentials=/etc/storage-L1.credentials,uid=998,gid=998,file_mode=0660,dir_mode=0770,_netdev
      TimeoutSec=30
      
      [Install]
      WantedBy=multi-user.target

  - path: /etc/storage-L1.credentials
    permissions: '0600'
    content: |
      username=u324047-sub5
      password=${STORAGE_L1}

  - path: /run/user/999/containers/auth.json
    content: |
      {
        \"auths\": {
                \"docker.io\": {
                        \"auth\": \"${DOCKER_IO}\"
                }
        }
      }

#swap:
#  filename: /swapfile
#  size: auto

runcmd:
#  - [usermod, -p, '*', ${USER_NAME}]
#  - [systemctl, daemon-reload]
#  - [systemctl, enable, wg-quick@wg0]
#  - [systemctl, start, wg-quick@wg0]
#  - [systemctl, restart, ssh]
  - [mkdir, -p, /mnt/storage-L1]
  - [systemctl, enable, storage-L1.mount]
  - [systemctl, start, storage-L1.mount]
  - [loginctl, enable-linger, nginxuser]
  - [usermod, --add-subuids, 100000-165535, nginxuser]
  - [usermod, --add-subgids, 100000-165535, nginxuser]
  - [git, clone, https://github.com/heroalex/server.git, /root/server]
  - [chmod, +x, /root/server/scripts/init_userhome.sh]
  - [chmod, +x, /root/server/scripts/init_nginxuser.sh]
  - [chmod, +x, /root/server/scripts/test_cloud-config.sh]
  - [/root/server/scripts/init_userhome.sh, ${USER_NAME}]
  - [/root/server/scripts/init_nginxuser.sh, nginxuser]
  - [su, -c, /home/nginxuser/init_nginx.sh, nginxuser]

#power_state:
#  mode: reboot
#  timeout: 300
#  condition: True