#cloud-config
users:
  - name: ${USER_NAME}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - \"${SSH_KEY}\"

  - name: registryuser
    shell: /bin/bash
    system: true

  - name: nginxuser
    shell: /bin/bash
    system: true

  - name: camuser
    shell: /bin/bash
    system: true

package_upgrade: true
packages:
  - wireguard
  - podman
  - slirp4netns
  - systemd-container
  - cifs-utils
  - git-lfs

write_files:
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      PrivateKey = ${WG_PRIV_KEY}
      ListenPort = 13231
      Address = 172.16.16.1/24

      [Peer]
      PublicKey = ${WG_PUB_KEY}
      AllowedIPs = 172.16.16.90/32
    permissions: '0600'

  - path: /etc/systemd/system/wg-quick@.service.d/override.conf
    content: |
      [Unit]
      Before=ssh.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
    permissions: '0644'

  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      Protocol 2
      PermitRootLogin no
      PubkeyAuthentication yes
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM no
      X11Forwarding no
      AllowTcpForwarding no
      AllowAgentForwarding no
      PermitTunnel no
      PrintMotd yes
      AcceptEnv LANG LC_*
      AllowUsers ${USER_NAME}
      ListenAddress 172.16.16.1
    permissions: '0600'

  - path: /etc/sysctl.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1
      vm.swappiness = 10
      vm.vfs_cache_pressure=50
      vm.overcommit_memory = 1
      net.ipv4.ip_unprivileged_port_start=80
    permissions: '0644'

  - path: /etc/systemd/system/home-registryuser-storage.mount
    content: |
      [Unit]
      Description=CIFS Mount for registryuser storage
      After=network-online.target
      Wants=network-online.target
      
      [Mount]
      What=//u324047-sub5.your-storagebox.de/u324047-sub5
      Where=/home/registryuser/storage
      Type=cifs
      Options=vers=3.0,uid=registryuser,gid=registryuser,credentials=/home/registryuser/.smbcredentials,file_mode=0660,dir_mode=0770,rw,_netdev
      TimeoutSec=30
      
      [Install]
      WantedBy=default.target
    permissions: '0644'

  - path: /home/registryuser/.smbcredentials
    content: |
      username=u324047-sub5
      password=${STORAGE_L1}
    permissions: '0600'

  - path: /etc/containers/registries.conf.d/00-local-registry.conf
    content: |
      unqualified-search-registries = [\"localhost:5000\"]
      
      [[registry]]
      location = \"localhost:5000\"
      insecure = true
      
      [[registry]]
      prefix=\"docker.io\"
      location = \"docker.io\"

      [[registry]]
      prefix=\"quay.io\"
      location = \"quay.io\"
    permissions: '0644'

swap:
  filename: /swapfile
  size: auto

runcmd:
  - [usermod, -p, '*', ${USER_NAME}]
  - [systemctl, daemon-reload]
  - [systemctl, enable, wg-quick@wg0]
  - [systemctl, start, wg-quick@wg0]
  - [systemctl, restart, ssh]
# init users
  - [ git, clone, https://github.com/heroalex/server.git, /root/server ]
# user
  - [ chmod, +x, /root/server/scripts/init_userhome.sh ]
  - [ /root/server/scripts/init_userhome.sh, ${USER_NAME} ]
# registryuser
  - [ chmod, +x, /root/server/scripts/init_registryuser.sh ]
  - [ /root/server/scripts/init_registryuser.sh, registryuser ]
# nginxuser
  - [chmod, +x, /root/server/scripts/init_nginxuser.sh]
  - [/root/server/scripts/init_nginxuser.sh, nginxuser]
# test_cloud-config
  - [chmod, +x, /root/server/scripts/test_cloud-config.sh]

power_state:
  mode: reboot
  timeout: 300
  condition: True