# This is a basic workflow that is manually triggered

name: Create Server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
      inputs:
        server_name:
          required: true
          type: string
        user_name:
          default: "al"
          required: true
          type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
            
    # Runs a single command using the runners shell
    - name: run script
      env:
        FW_ID: ${{ secrets.FW_ID }}
        server_name: ${{ inputs.server_name }}
        IP_ID: ${{ secrets.IP_ID }}
        SSH_ID: ${{ secrets.SSH_ID }}
        USER_NAME: ${{ inputs.user_name }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        WG_PRIV_KEY: ${{ secrets.WG_PRIV_KEY }}
        WG_PUB_KEY: ${{ secrets.WG_PUB_KEY }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: bash scripts/create_server.sh
